import { DBConfig } from 'ngx-indexed-db';

export const dbConfig: DBConfig = {
  name: 'MyDb',
  version: 1,
  objectStoresMeta: [
    {
      store: 'schedule',
      storeConfig: { keyPath: 'id', autoIncrement: false },
      storeSchema: [
        {
          name: 'idModuleClass',
          keypath: 'idModuleClass',
          options: { unique: false },
        },
        { name: 'name', keypath: 'name', options: { unique: false } },
        { name: 'idRoom', keypath: 'idRoom', options: { unique: false } },
        { name: 'note', keypath: 'note', options: { unique: false } },
        { name: 'shift', keypath: 'shift', options: { unique: false } },
        { name: 'date', keypath: 'date', options: { unique: false } },
        { name: 'color', keypath: 'color', options: { unique: false } },
        {
          name: 'moduleName',
          keypath: 'moduleName',
          options: { unique: false },
        },
        { name: 'teacher', keypath: 'teacher', options: { unique: false } },
        {
          name: 'fixedSchedules',
          keypath: 'fixedSchedules',
          options: { unique: false },
        },
      ],
    },
    {
      store: 'exam',
      storeConfig: { keyPath: 'id', autoIncrement: false },
      storeSchema: [
        {
          name: 'idModuleClass',
          keypath: 'idModuleClass',
          options: { unique: false },
        },
        { name: 'name', keypath: 'name', options: { unique: false } },
        { name: 'method', keypath: 'method', options: { unique: false } },
        { name: 'startAt', keypath: 'startAt', options: { unique: false } },
        { name: 'endAt', keypath: 'endAt', options: { unique: false } },
        { name: 'idRoom', keypath: 'idRoom', options: { unique: false } },
        { name: 'note', keypath: 'note', options: { unique: false } },
        { name: 'teacher', keypath: 'teacher', options: { unique: false } },
        {
          name: 'numberOfStudents',
          keypath: 'numberOfStudents',
          options: { unique: false },
        },
        { name: 'credit', keypath: 'credit', options: { unique: false } },
      ],
    },
    {
      store: 'departmentSchedule',
      storeConfig: { keyPath: 'id', autoIncrement: false },
      storeSchema: [
        {
          name: 'idModuleClass',
          keypath: 'idModuleClass',
          options: { unique: false },
        },
        { name: 'name', keypath: 'name', options: { unique: false } },
        { name: 'idRoom', keypath: 'idRoom', options: { unique: false } },
        { name: 'note', keypath: 'note', options: { unique: false } },
        { name: 'shift', keypath: 'shift', options: { unique: false } },
        { name: 'date', keypath: 'date', options: { unique: false } },
        { name: 'color', keypath: 'color', options: { unique: false } },
        {
          name: 'moduleName',
          keypath: 'moduleName',
          options: { unique: false },
        },
        { name: 'teacher', keypath: 'teacher', options: { unique: false } },
        {
          name: 'fixedSchedules',
          keypath: 'fixedSchedules',
          options: { unique: false },
        },
      ],
    },
    {
      store: 'departmentExam',
      storeConfig: { keyPath: 'id', autoIncrement: false },
      storeSchema: [
        {
          name: 'idModuleClass',
          keypath: 'idModuleClass',
          options: { unique: false },
        },
        { name: 'name', keypath: 'name', options: { unique: false } },
        { name: 'method', keypath: 'method', options: { unique: false } },
        { name: 'startAt', keypath: 'startAt', options: { unique: false } },
        { name: 'endAt', keypath: 'endAt', options: { unique: false } },
        { name: 'idRoom', keypath: 'idRoom', options: { unique: false } },
        { name: 'note', keypath: 'note', options: { unique: false } },
        { name: 'teacher', keypath: 'teacher', options: { unique: false } },
        {
          name: 'numberOfStudents',
          keypath: 'numberOfStudents',
          options: { unique: false },
        },
        { name: 'credit', keypath: 'credit', options: { unique: false } },
      ],
    },
    {
      store: 'googleCalendarEvents',
      storeConfig: { keyPath: 'id', autoIncrement: false },
      storeSchema: [
        {
          name: 'anyoneCanAddSelf',
          keypath: 'anyoneCanAddSelf',
          options: { unique: false },
        },
        {
          name: 'attendeesOmitted',
          keypath: 'attendeesOmitted',
          options: { unique: false },
        },
        { name: 'attendees', keypath: 'attendees', options: { unique: false } },
        { name: 'colorId', keypath: 'colorId', options: { unique: false } },
        { name: 'created', keypath: 'created', options: { unique: false } },
        {
          name: 'description',
          keypath: 'description',
          options: { unique: false },
        },
        {
          name: 'endTimeUnspecified',
          keypath: 'endTimeUnspecified',
          options: { unique: false },
        },
        { name: 'etag', keypath: 'etag', options: { unique: false } },
        { name: 'eventType', keypath: 'eventType', options: { unique: false } },
        {
          name: 'guestsCanInviteOthers',
          keypath: 'guestsCanInviteOthers',
          options: { unique: false },
        },
        {
          name: 'guestsCanModify',
          keypath: 'guestsCanModify',
          options: { unique: false },
        },
        {
          name: 'guestsCanSeeOtherGuests',
          keypath: 'guestsCanSeeOtherGuests',
          options: { unique: false },
        },
        {
          name: 'hangoutLink',
          keypath: 'hangoutLink',
          options: { unique: false },
        },
        { name: 'htmlLink', keypath: 'htmlLink', options: { unique: false } },
        { name: 'iCalUID', keypath: 'iCalUID', options: { unique: false } },
        { name: 'id', keypath: 'id', options: { unique: false } },
        { name: 'kind', keypath: 'kind', options: { unique: false } },
        { name: 'location', keypath: 'location', options: { unique: false } },
        { name: 'locked', keypath: 'locked', options: { unique: false } },
        {
          name: 'privateCopy',
          keypath: 'privateCopy',
          options: { unique: false },
        },
        {
          name: 'recurrence',
          keypath: 'recurrence',
          options: { unique: false },
        },
        {
          name: 'recurringEventId',
          keypath: 'recurringEventId',
          options: { unique: false },
        },
        { name: 'sequence', keypath: 'sequence', options: { unique: false } },
        { name: 'status', keypath: 'status', options: { unique: false } },
        { name: 'summary', keypath: 'summary', options: { unique: false } },
        {
          name: 'transparency',
          keypath: 'transparency',
          options: { unique: false },
        },
        { name: 'updated', keypath: 'updated', options: { unique: false } },
        {
          name: 'visibility',
          keypath: 'visibility',
          options: { unique: false },
        },
        { name: 'creator', keypath: 'creator', options: { unique: false } },
        { name: 'organizer', keypath: 'organizer', options: { unique: false } },
        { name: 'start', keypath: 'start', options: { unique: false } },
        { name: 'end', keypath: 'end', options: { unique: false } },
        { name: 'reminders', keypath: 'reminders', options: { unique: false } },
        { name: 'calendar', keypath: 'calendar', options: { unique: false } },
      ],
    },
  ],
};
