name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug in the TSS
labels: ['bug']

body:
  - type: dropdown
    id: affected-libs
    attributes:
      label: Which lib(s) are the source of the bug?
      options:
        - core
        - calendar
        - config
        - error
        - exam
        - feedback
        - login
        - reset-password
        - settings
        - shared
        - shell
        - statistic
        - teaching-schedule
        - user-info
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: blocking
    attributes:
      label: Is this issue blocking you?
      options:
        - Non-Blocking
        - Blocking
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
    validations:
      required: true

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
