export class PermissionConstant {
  public static BASIC_PERMISSION = 1;
  public static SEND_NOTIFICATION_TO_ALL_STUDENTS = 2;
  public static SEND_NOTIFICATION_TO_STUDENT_BY_SCHOOL_YEAR = 3;
  public static SEND_NOTIFICATION_TO_STUDENT_BY_FACULTY = 4;
  public static SEND_NOTIFICATION_TO_STUDENT_BY_MANAGING_CLASS = 5;
  public static SEND_NOTIFICATION_TO_STUDENT_BY_MODULE_CLASS = 6;
  public static SEND_NOTIFICATION_TO_SPECIFIC_STUDENT = 7;
  public static SEND_NOTIFICATION_TO_TEACHER = 8;
  public static DIVIDE_SCHEDULE = 9;
  public static AUTHORIZE_DEPARTMENT_PERMISSION = 10;
  public static REQUEST_CHANGE_TEACHING_SCHEDULE = 11;
  public static ACCEPT_CHANGE_TEACHING_SCHEDULE = 12;
  public static MANAGE_ROOM = 13;
  public static IMPORT_DATA = 14;
  public static AUTHORIZE_PERMISSION = 15;
  public static SEE_FEEDBACK = 16;
  public static SEE_DEPARTMENT_EXAM_SCHEDULE = 17;
}
